=== uo293686/SEW/xml/circuito.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.uniovi.es" targetNamespace="http://www.uniovi.es" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name" />
				<xs:element ref="length" />
				<xs:element ref="width" />
				<xs:element ref="date" />
				<xs:element ref="hour" />
				<xs:element ref="laps" />
				<xs:element ref="location" />
				<xs:element ref="country" />
				<xs:element ref="sponsor" />
				<xs:element ref="references" />
				<xs:element ref="photos" />
				<xs:element ref="videos" />
				<xs:element ref="coordinates" />
				<xs:element ref="tramos" />
				<xs:element ref="winnerinfo" />
				<xs:element ref="qualified" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="name" type="xs:string" />
	<xs:element name="length">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:integer">
					<xs:attribute name="unit" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="width">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:double">
					<xs:attribute name="unit" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="date" type="xs:date" />
	<xs:element name="hour" type="xs:dateTime" />
	<xs:element name="laps" type="xs:integer" />
	<xs:element name="location" type="xs:string" />
	<xs:element name="country" type="xs:string" />
	<xs:element name="sponsor" type="xs:string" />
	<xs:element name="references">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="reference" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="reference" type="xs:string" />
	<xs:element name="photos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="photo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="photo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="phototitle" />
				<xs:element ref="imgfilename" />
				<xs:element ref="imgformat" />
				<xs:element ref="imgurl" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="phototitle" type="xs:string" />
	<xs:element name="imgfilename" type="xs:string" />
	<xs:element name="imgformat" type="xs:string" />
	<xs:element name="imgurl" type="xs:string" />
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="videotitle" />
				<xs:element ref="filename" />
				<xs:element ref="format" />
				<xs:element ref="url" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="videotitle" type="xs:string" />
	<xs:element name="filename" type="xs:string" />
	<xs:element name="format" type="xs:string" />
	<xs:element name="url" type="xs:string" />
	<xs:element name="coordinates">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="latitud" />
				<xs:element ref="longitud" />
				<xs:element ref="height" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="latitud" type="xs:string" />
	<xs:element name="longitud" type="xs:string" />
	<xs:element name="height">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:integer">
					<xs:attribute name="unit" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="distance" />
				<xs:element ref="endcoords" />
				<xs:element ref="number" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="distance">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:integer">
					<xs:attribute name="unit" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="endcoords">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="endlatitud" />
				<xs:element ref="endlongitud" />
				<xs:element ref="endheight" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="endlatitud" type="xs:string" />
	<xs:element name="endlongitud" type="xs:string" />
	<xs:element name="endheight">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="unit" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="number" type="xs:integer" />
	<xs:element name="winnerinfo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="winner" />
				<xs:element ref="time" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="winner" type="xs:string" />
	<xs:element name="time" type="xs:duration" />
	<xs:element name="qualified">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="driver" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="driver" type="xs:string" />
</xs:schema>

=== uo293686/SEW/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuito xmlns="http://www.uniovi.es"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.uniovi.es circuito.xsd"
>
    <name>Autodromo Internazionale del Mugello</name>
    <length unit="metros">5245</length>
    <width unit="metros">11.9</width>
    <date>2025-06-22</date>
    <hour>2025-06-22T14:00:00</hour>
    <laps>23</laps>
    <location>Scarperia e San Piero, Florencia</location>
    <country>Italia</country>
    <sponsor>Brembo</sponsor>
    <references>
        <reference>https://www.motogp.com/es/calendar/2025/event/italy/ae539677-70a6-4642-aee4-6d6cc5979f67?tab=circuit-info</reference>
        <reference>https://en.wikipedia.org/wiki/Mugello_Circuit</reference>
        <reference>https://mugellocircuit.com/it/pista/descrizione-pista</reference>
    </references>
    <photos>
        <photo>
            <phototitle>Vista panorámica</phototitle>
            <imgfilename>panorama.jpg</imgfilename>
            <imgformat>image/jpeg</imgformat>
            <imgurl>multimedia/panorama.jpg</imgurl>
        </photo>
        <photo>
            <phototitle>Parrilla de salida</phototitle>
            <imgfilename>parrilla_de_salida.jpg</imgfilename>
            <imgformat>image/jpeg</imgformat>
            <imgurl>multimedia/parrilla_de_salida.jpg</imgurl>
        </photo>
        <photo>
            <phototitle>Secciones</phototitle>
            <imgfilename>secciones.jpg</imgfilename>
            <imgformat>image/jpeg</imgformat>
            <imgurl>multimedia/secciones.jpg</imgurl>
        </photo>
    </photos>
    <videos>
        <video>
            <videotitle>Recorrido del circuito</videotitle>
            <filename>recorrido_circuito.mp4</filename>
            <format>video/mp4</format>
            <url>multimedia/recorrido_circuito.mp4</url>
        </video>
    </videos>
    <coordinates>
        <latitud>43.997611</latitud>
        <longitud>11.371472</longitud>
        <height unit="metros">292</height>
    </coordinates>
    <tramos>
        <tramo>
            <distance unit="metros">681</distance>
            <endcoords>
              <endlatitud>43.99758265447097</endlatitud>
              <endlongitud>11.37149650090408</endlongitud>
              <endheight unit="metros">256</endheight>
            </endcoords>
            <number>1</number>
          </tramo>
          <tramo>
            <distance unit="metros">47</distance>
            <endcoords>
              <endlatitud>44.00311453966479</endlatitud>
              <endlongitud>11.3751547154662</endlongitud>
              <endheight unit="metros">268</endheight>
            </endcoords>
            <number>2</number>
          </tramo>
          <tramo>
            <distance unit="metros">44</distance>
            <endcoords>
              <endlatitud>44.00326105947403</endlatitud>
              <endlongitud>11.37570878970725</endlongitud>
              <endheight unit="metros">268</endheight>
            </endcoords>
            <number>3</number>
          </tramo>
          <tramo>
            <distance unit="metros">31</distance>
            <endcoords>
              <endlatitud>44.00305697102322</endlatitud>
              <endlongitud>11.37618261429373</endlongitud>
              <endheight unit="metros">269</endheight>
            </endcoords>
            <number>4</number>
          </tramo>
          <tramo>
            <distance unit="metros">152</distance>
            <endcoords>
              <endlatitud>44.00279474050314</endlatitud>
              <endlongitud>11.37631539345632</endlongitud>
              <endheight unit="metros">272</endheight>
            </endcoords>
            <number>5</number>
          </tramo>
          <tramo>
            <distance unit="metros">26</distance>
            <endcoords>
              <endlatitud>44.00144864422621</endlatitud>
              <endlongitud>11.37602884708407</endlongitud>
              <endheight unit="metros">280</endheight>
            </endcoords>
            <number>6</number>
          </tramo>
          <tramo>
            <distance unit="metros">87</distance>
            <endcoords>
              <endlatitud>44.00123473420027</endlatitud>
              <endlongitud>11.37615197789951</endlongitud>
              <endheight unit="metros">280</endheight>
            </endcoords>
            <number>7</number>
          </tramo>
          <tramo>
            <distance unit="metros">42</distance>
            <endcoords>
              <endlatitud>44.00082549002367</endlatitud>
              <endlongitud>11.37707689242104</endlongitud>
              <endheight unit="metros">282</endheight>
            </endcoords>
            <number>8</number>
          </tramo>
          <tramo>
            <distance unit="metros">41</distance>
            <endcoords>
              <endlatitud>44.00048844529314</endlatitud>
              <endlongitud>11.37731248647307</endlongitud>
              <endheight unit="metros">284</endheight>
            </endcoords>
            <number>9</number>
          </tramo>
          <tramo>
            <distance unit="metros">349</distance>
            <endcoords>
              <endlatitud>44.000123388194</endlatitud>
              <endlongitud>11.37722021193938</endlongitud>
              <endheight unit="metros">285</endheight>
            </endcoords>
            <number>10</number>
          </tramo>
          <tramo>
            <distance unit="metros">41</distance>
            <endcoords>
              <endlatitud>43.99749618652729</endlatitud>
              <endlongitud>11.37482289856738</endlongitud>
              <endheight unit="metros">281</endheight>
            </endcoords>
            <number>11</number>
          </tramo>
          <tramo>
            <distance unit="metros">55</distance>
            <endcoords>
              <endlatitud>43.99712714781948</endlatitud>
              <endlongitud>11.37485361403651</endlongitud>
              <endheight unit="metros">282</endheight>
            </endcoords>
            <number>12</number>
          </tramo>
          <tramo>
            <distance unit="metros">43</distance>
            <endcoords>
              <endlatitud>43.99669646941431</endlatitud>
              <endlongitud>11.37519343096652</endlongitud>
              <endheight unit="metros">280</endheight>
            </endcoords>
            <number>13</number>
          </tramo>
          <tramo>
            <distance unit="metros">313</distance>
            <endcoords>
              <endlatitud>43.99631721774779</endlatitud>
              <endlongitud>11.3751050588706</endlongitud>
              <endheight unit="metros">279</endheight>
            </endcoords>
            <number>14</number>
          </tramo>
          <tramo>
            <distance unit="metros">120</distance>
            <endcoords>
              <endlatitud>43.99415608060823</endlatitud>
              <endlongitud>11.37260975257893</endlongitud>
              <endheight unit="metros">265</endheight>
            </endcoords>
            <number>15</number>
          </tramo>
          <tramo>
            <distance unit="metros">58</distance>
            <endcoords>
              <endlatitud>43.99407349901766</endlatitud>
              <endlongitud>11.37111310318959</endlongitud>
              <endheight unit="metros">255</endheight>
            </endcoords>
            <number>16</number>
          </tramo>
          <tramo>
            <distance unit="metros">55</distance>
            <endcoords>
              <endlatitud>43.99386907668737</endlatitud>
              <endlongitud>11.37045052654332</endlongitud>
              <endheight unit="metros">251</endheight>
            </endcoords>
            <number>17</number>
          </tramo>
          <tramo>
            <distance unit="metros">157</distance>
            <endcoords>
              <endlatitud>43.99346607758238</endlatitud>
              <endlongitud>11.37004587067652</endlongitud>
              <endheight unit="metros">247</endheight>
            </endcoords>
            <number>18</number>
          </tramo>
          <tramo>
            <distance unit="metros">61</distance>
            <endcoords>
              <endlatitud>43.99213143966437</endlatitud>
              <endlongitud>11.36940018138305</endlongitud>
              <endheight unit="metros">243</endheight>
            </endcoords>
            <number>19</number>
          </tramo>
          <tramo>
            <distance unit="metros">74</distance>
            <endcoords>
              <endlatitud>43.9917141063755</endlatitud>
              <endlongitud>11.36890583493548</endlongitud>
              <endheight unit="metros">243</endheight>
            </endcoords>
            <number>20</number>
          </tramo>
          <tramo>
            <distance unit="metros">184</distance>
            <endcoords>
              <endlatitud>43.99153005289496</endlatitud>
              <endlongitud>11.36801983579136</endlongitud>
              <endheight unit="metros">246</endheight>
            </endcoords>
            <number>21</number>
          </tramo>
          <tramo>
            <distance unit="metros">59</distance>
            <endcoords>
              <endlatitud>43.99227024676193</endlatitud>
              <endlongitud>11.36597013843274</endlongitud>
              <endheight unit="metros">259</endheight>
            </endcoords>
            <number>22</number>
          </tramo>
          <tramo>
            <distance unit="metros">305</distance>
            <endcoords>
              <endlatitud>43.99276921851885</endlatitud>
              <endlongitud>11.3657439242495</endlongitud>
